### ISSUE TITLE
Nothing happens, when import settings...

### ISSUE THREAD

**Issue by itProfi** [ravendmaster/linear-mqtt-dashboard#13]
When i try import previosly saved setting on application, the nothing happens....On some other devices - the same problem..

**Comment by Lstt2005** [comment]
Correct

**Comment by heX16** [comment]
You import settings from old application to new version application?

**Comment by heX16** [comment]
In the new version (from 2018) the format of the _config file_ has changed ([detail](https://github.com/ravendmaster/linear-mqtt-dashboard/pull/9)).
When updating an application, its configuration must go without damage.
But after the upgrade, you **must re-export** your _config file_.

If you not have program with internal configuration and have only _config file_:
1) Install old program version (at 2016). I understand that it will not be easy to find this version - you can ask the @ravendmaster (or try find in internet).
2) Import _config file_.
3) Upgrade to new version.

if deleting data when installing the new version:
1.1) Install "titanuim backup" (or other backup utils).
2.1) Make application data backup.
3.1) Restore backup.

P.S. Or you can fix the _config file_ manually - but this requires knowledge of the JSON format. I can tell you what you need to fix.

**Comment by itProfi** [comment]
Ok, all fine!
