### ISSUE TITLE
Fullscreen mode...

### ISSUE THREAD

**Issue by itProfi** [ravendmaster/linear-mqtt-dashboard#14]
Is it possible make new mode in application - Fullscreen mode? In some cases very need this mode...

**Comment by ravendmaster** [comment]
Implemented. Take from Google Play  (you need to be a tester). The source code will not be published in this repositorie, because the project moves to Kotlin.

**Comment by itProfi** [comment]
Спасибо большое! А если вкратце, можно поподробнее про Kotlin?
