### ISSUE TITLE
linear-mqtt-dashboard version on github vs. google play

### ISSUE THREAD

**Issue by hmueller01** [ravendmaster/linear-mqtt-dashboard#5]
Hi!
It looks like google play version is newer (2.2.7, 21. Jan. 2017) than master github version (2.2.1). Is it possible to update github to the latest version? I like to add some features and doing this on an old version is a shame.

Thanks
Holger

**Comment by ppontre** [comment]
Me too: What about translation in more euro langs ?
thnx & regards
Paolo

**Comment by heX16** [comment]
Да, меня тоже интересует этот вопрос - я хочу помочь доработать одну фичу. Но хочется заранее знать дальнейшую судьбу моего "pull request".

**Comment by jedi7** [comment]
Guys, the new version is probably from this repo: https://github.com/ravendmaster/linear-mqtt-dashboard-kotlin
It appears like he started to use Kotlin. So this repo is probably dead :(
